### ISSUE TITLE
Retrieve the "lastPwdSet" and "mail" attributes from Get-ADDBAccount and Get-ADReplAccount

### ISSUE THREAD

**Issue by yanncam** [MichaelGrafnetter/DSInternals#134]
Hello,

I open an issue for enhancement. I have check issues (open/closed) and made some tests with `Get-ADDBAccount` and `Get-ADReplAccount` but I can't retrieve the following user account's attributes that I need :

- `mail` : the corporate email of the identity specified stored in the Active Directory
- `lastPwdSet` : the timestamp of the last update of the password

As example, from an `ntds.dit` file, I have tried:

```
PS C:\Users\X\Desktop\Active Directory> Get-ADDBAccount -samaccountname krbtgt -BootKey $key -DatabasePath ".\ntds.dit"

DistinguishedName: CN=krbtgt,CN=Users,DC=opmanagement,DC=local
Sid: S-1-5-21-2576180771-3553906584-3249235270-502
Guid: 889fc01f-ef4a-4f0a-97aa-7b628463346d
SamAccountName: krbtgt
SamAccountType: User
UserPrincipalName:
PrimaryGroupId: 513
SidHistory:
Enabled: False
UserAccountControl: Disabled, NormalAccount
SupportedEncryptionTypes: Default
AdminCount: True
Deleted: False
LastLogonDate:
DisplayName:
GivenName:
Surname:
Description: Key Distribution Center Service Account
ServicePrincipalName: {kadmin/changepw}
SecurityDescriptor: DiscretionaryAclPresent, SystemAclPresent, DiscretionaryAclAutoInherited, SystemAclAutoInherited,
DiscretionaryAclProtected, SelfRelative
Owner: S-1-5-21-2576180771-3553906584-3249235270-512
Secrets
  [... REDACTED ...]
Key Credentials:
Credential Roaming
  Created:
  Modified:
  Credentials:
```

In this example, there is the `LastLogonDate` attribute (obviously empty for *krbtgt*, but not for other users).
But no "LastPwdSet" nor "mail".

When I pipe the previous command and `select *`, some others attributes are available:

```
PS C:\Users\X\Desktop\Active Directory> Get-ADDBAccount -samaccountname krbtgt -BootKey $key -DatabasePath ".\ntds.dit" | select *


DistinguishedName             : CN=krbtgt,CN=Users,DC=opmanagement,DC=local
Sid                           : S-1-5-21-2576180771-3553906584-3249235270-502
SidHistory                    :
SecurityDescriptor            : System.Security.AccessControl.RawSecurityDescriptor
Guid                          : 889fc01f-ef4a-4f0a-97aa-7b628463346d
DisplayName                   :
Description                   : Key Distribution Center Service Account
GivenName                     :
Surname                       :
Enabled                       : False
UserAccountControl            : Disabled, NormalAccount
SupportedEncryptionTypes      : Default
SupportsKerberosAESEncryption : False
Deleted                       : False
LastLogon                     :
LastLogonTimestamp            :
LastLogonDate                 :
UserPrincipalName             :
SamAccountName                : krbtgt
LogonName                     : OPMANAGEMENT\krbtgt
PrimaryGroupId                : 513
SamAccountType                : User
AdminCount                    : True
ServicePrincipalName          : {kadmin/changepw}
NTHash                        : [... REDACTED ...]
LMHash                        :
NTHashHistory                 : [... REDACTED ...]
LMHashHistory                 : [... REDACTED ...]
SupplementalCredentials       : DSInternals.Common.Data.SupplementalCredentials
RoamedCredentialsCreated      :
RoamedCredentialsModified     :
RoamedCredentials             :
KeyCredentials                : {}
```

In the previous output, we can see the new `LastLogonTimestamp` or `LastLogon` attributes available.
But no `LastPwdSet` nor `mail`.

Same with the pipe `| Format-List -Property *`.

- Can you confirm to me that these attributes are not returned throught `Get-ADDBAccount` and `Get-ADReplAccount` (or I'm totaly blind 😎) ?
- Do you think it is possible to retrieve `LastPwdSet` and `mail` attributes via `Get-ADDBAccount` and `Get-ADReplAccount` ?

Thank you again for your great work,

Sincerely,
